import { FaAmazon, FaMicrosoft } from 'react-icons/fa'
import {
  SiAcer, SiAirbnb, SiAircanada, SiAirfrance, SiAldisud, SiAliexpress, SiAllegro, SiAmd, SiAmericanairlines, SiApple, SiApplepay, SiAral, SiAsda, SiAsus, SiAuchan,
  SiBankofamerica, SiBarclays, SiBinance, SiBookingdotcom, SiBose, SiBritishairways, SiBunq, SiBurgerking, SiBvg, SiCarrefour,
  SiCashapp, SiChase, SiCoinbase, SiCommerzbank, SiCoop, SiCorsair, SiDazn, SiDeliveroo,
  SiDelta, SiDeutschebahn, SiDeutschebank, SiDeutschepost, SiDeutschetelekom, SiDhl, SiDiscord, SiDm, SiDoordash, SiDuolingo, SiEasyjet, SiEbay, SiEdeka,
  SiEmirates, SiEpicgames, SiEpson, SiEtihadairways, SiEtsy, SiExpedia, SiFiat, SiFord, SiGithub, SiGlovo, SiGojek, SiGooglepay, SiGrab, SiHellofresh, SiHilton, SiHonda, SiHotelsdotcom, SiHp, SiHsbc, SiHuawei, SiHyundai, SiIkea, SiIntel, SiJusteat, SiKaufland, SiKfc,
  SiKia, SiKlarna, SiKlm, SiLenovo, SiLg, SiLidl, SiLufthansa, SiLyft, SiMarriott, SiMastercard, SiMazda, SiMcdonalds, SiMediamarkt, SiMoneygram, SiMonzo,
  SiMorrisons, SiMsi, SiN26, SiNetflix, SiNetto, SiNike, SiNissan, SiNvidia, SiO2, SiOpel, SiOrange, SiPayoneer, SiPaypal, SiPenny,
  SiPeugeot, SiPlaystation, SiQantas, SiQatarairways, SiRazer, SiRenault, SiRevolut, SiRewe, SiRossmann, SiRyanair, SiSamsung, SiSeagate, SiSeat, SiSennheiser, SiShell, SiShopee, SiSingaporeairlines, SiSkoda, SiSky, SiSony, SiSouthwestairlines, SiSparkasse,
  SiSpotify, SiStarbucks, SiStarlingbank, SiSteam, SiStrava, SiStripe, SiTarget, SiTesco, SiTesla, SiToyota, SiTripadvisor, SiTrivago, SiTui, SiTurkishairlines, SiTwitch, SiUber,
  SiUbereats, SiUnitedairlines, SiVenmo, SiVinted, SiVisa, SiVodafone, SiVolvo,
  SiWesternunion, SiWise, SiWizzair, SiXiaomi, SiYoutube,
  SiZabka, SiZalando, SiZara
} from 'react-icons/si'

import {
  C24Logo,
  ComdirectLogo,
  ConsorsbankLogo,
  DkbLogo,
  IngLogo,
  PostbankLogo,
  ScalableCapitalLogo,
  SpardaBankLogo,
  TargobankLogo,
  TomorrowLogo,
  TradeRepublicLogo,
  VolksbankLogo,
} from './bank-logos'
import {
  AudiLogo,
  BmwLogo,
  MercedesLogo,
  PorscheLogo,
  VolkswagenLogo,
} from './car-logos'
import {
  AokLogo,
  BarmerLogo,
  DakLogo,
  DocMorrisLogo,
  ShopApothekeLogo,
  TkLogo,
} from './health-logos'
import {
  BauhausLogo,
  Check24Logo,
  DellLogo,
  HornbachLogo,
  ObiLogo,
  SumupLogo,
  TchiboLogo,
} from './retail-logos'
import {
  CanonLogo,
  HpLogo,
  LogitechLogo,
  MicrosoftLogo,
  PhilipsLogo,
} from './tech-logos'
import {
  AsfinagLogo,
  AviaLogo,
  BpLogo,
  EasyParkLogo,
  EnbwLogo,
  EniLogo,
  EssoLogo,
  FairParkenLogo,
  FastnedLogo,
  FlixLogo,
  HvvLogo,
  IonityLogo,
  JetLogo,
  OebbLogo,
  RmvLogo,
  SixtLogo,
  TurmoelLogo,
  VrrLogo,
} from './transit-logos'
import {
  AlltoursLogo,
  CondorLogo,
  DertourLogo,
  EurowingsLogo,
  SchauinslandLogo,
  TuiLogo,
} from './travel-logos'
import type { IconComponent } from './types'
import {
  AllianzLogo,
  BeitragsserviceLogo,
  EinsUndEinsLogo,
  EonLogo,
  HukLogo,
  SuewagLogo,
  VattenfallLogo,
} from './utility-logos'

export const MERCHANT_LOGOS: Record<string, IconComponent> = {
  SiNetflix, SiSpotify, SiUber, SiStarbucks, SiSteam, SiMcdonalds,
  SiIkea, SiApple, SiPaypal, SiAirbnb, SiNike, SiDm, SiRewe,
  SiKaufland, SiShell, SiDeutschebahn, SiDeutschetelekom, SiVodafone, SiO2,
  FaAmazon, SiAldisud, SiAral, SiEdeka, SiLidl,
  SiZalando, SiTesco, SiShopee, SiOrange, SiGrab, SiGojek, SiDeliveroo,
  SiCarrefour, SiBookingdotcom, SiAllegro, SiJusteat, SiEbay, SiAuchan,
  SiZabka, SiAsda, SiMorrisons, SiCoop, SiTarget, SiBurgerking, SiKfc,
  SiDoordash, SiUbereats, SiRevolut, SiWise, SiKlarna, SiN26, SiMastercard,
  SiVisa, SiZara, SiLyft, SiYoutube, SiTwitch, SiPlaystation, SiSparkasse,
  SiWesternunion, SiMoneygram, SiApplepay, SiBankofamerica, SiBarclays, SiBinance,
  SiCashapp, SiChase, SiCoinbase, SiCommerzbank, SiDeutschebank, SiGlovo,
  SiGooglepay, SiHsbc, SiMonzo, SiPayoneer, SiStripe, SiVenmo,
  SiRossmann, SiMediamarkt, SiVinted, SiAliexpress, SiEtsy, SiHellofresh,
  SiBunq, SiStarlingbank, SiEpicgames, SiDiscord, SiGithub, SiDuolingo, SiStrava,
  ComdirectLogo, DkbLogo, IngLogo, PostbankLogo, TradeRepublicLogo,
  ScalableCapitalLogo, VolksbankLogo, TargobankLogo, SpardaBankLogo, C24Logo, ConsorsbankLogo,
  TomorrowLogo, TomorrowBankLogo: TomorrowLogo,
  RmvLogo, HvvLogo, FlixLogo, OebbLogo, VrrLogo, BpLogo,
  SiTesla, JetLogo, EssoLogo, AviaLogo, EniLogo, TurmoelLogo, AsfinagLogo, IonityLogo, EnbwLogo, FastnedLogo, SixtLogo,
  FairParkenLogo, EasyParkLogo,
  SiTui, TuiLogo,
  SiAirfrance, SiAmericanairlines, SiAircanada, SiBritishairways, SiBvg, SiDelta, SiEasyjet, SiEmirates,
  SiEtihadairways, SiExpedia, SiHilton, SiHotelsdotcom, SiKlm, SiLufthansa, SiMarriott, SiNetto,
  SiPenny, SiQantas, SiQatarairways, SiRyanair, SiSingaporeairlines, SiSouthwestairlines, SiTripadvisor,
  SiTrivago, SiTurkishairlines, SiUnitedairlines, SiWizzair,
  DertourLogo, AlltoursLogo, SchauinslandLogo, Check24Logo, SumupLogo,
  SiDhl, SiDeutschepost, SiDazn, SiSky,
  BeitragsserviceLogo, TkLogo, AokLogo, EinsUndEinsLogo,
  SuewagLogo, EonLogo, VattenfallLogo, EurowingsLogo, CondorLogo,
  BarmerLogo, DakLogo, ShopApothekeLogo, DocMorrisLogo,
  ObiLogo, BauhausLogo, HornbachLogo, TchiboLogo, DellLogo,
  SiDell: DellLogo,
  SiHp,
  HpLogo,
  SiLenovo,
  SiSamsung,
  SiAsus,
  SiAcer,
  AcerLogo: SiAcer,
  SiMsi,
  MsiLogo: SiMsi,
  SiSony,
  SonyLogo: SiSony,
  SiLg,
  LgLogo: SiLg,
  MicrosoftLogo,
  FaMicrosoft,
  SiMicrosoft: MicrosoftLogo,
  LogitechLogo,
  CanonLogo,
  PhilipsLogo,
  SiNvidia,
  NvidiaLogo: SiNvidia,
  SiAmd,
  AmdLogo: SiAmd,
  SiIntel,
  IntelLogo: SiIntel,
  SiRazer,
  RazerLogo: SiRazer,
  SiXiaomi,
  XiaomiLogo: SiXiaomi,
  SiBose,
  BoseLogo: SiBose,
  SiCorsair,
  SiSennheiser,
  SiSeagate,
  SiEpson,
  SiHuawei,
  AllianzLogo, HukLogo,
  MercedesLogo,
  MercedesBenzLogo: MercedesLogo,
  BmwLogo,
  AudiLogo,
  VolkswagenLogo,
  VwLogo: VolkswagenLogo,
  PorscheLogo,
  SiToyota,
  SiFord,
  SiVolvo,
  SiRenault,
  SiSkoda,
  SiSeat,
  SiOpel,
  SiHyundai,
  SiHonda,
  SiKia,
  SiMazda,
  SiNissan,
  SiPeugeot,
  SiFiat
}
