import { FaAws, FaMicrosoft } from 'react-icons/fa'
import {
  SiAcer, SiAirbnb, SiAircanada, SiAirfrance, SiAldisud, SiAliexpress, SiAllegro, SiAmd, SiAmericanairlines, SiApplepay, SiAsda, SiAsus, SiAuchan,
  SiBankofamerica, SiBarclays, SiBinance, SiBose, SiBritishairways, SiBunq, SiBurgerking, SiCarrefour,
  SiCashapp, SiChase, SiCoop, SiCorsair, SiDazn, SiDeliveroo,
  SiDelta, SiDeutschepost, SiDeutschetelekom, SiDhl, SiDigitalocean, SiDiscord, SiDm, SiDoordash, SiDuolingo, SiEasyjet, SiEdeka,
  SiEmirates, SiEpicgames, SiEpson, SiEtihadairways, SiEtsy, SiExpedia, SiFiat, SiFord, SiFreenet, SiGithub, SiGlovo, SiGojek, SiGrab, SiHellofresh, SiHetzner, SiHilton, SiHonda, SiHotelsdotcom, SiHp, SiHsbc, SiHuawei, SiHyundai, SiIntel, SiIonos, SiJusteat, SiKaufland, SiKfc,
  SiKia, SiKlm, SiLenovo, SiLg, SiLidl, SiLufthansa, SiLyft, SiMarriott, SiMastercard, SiMazda, SiMoneygram, SiMonzo,
  SiMorrisons, SiMsi, SiN26, SiNetcup, SiNetto, SiNike, SiNissan, SiNvidia, SiOpel, SiOrange, SiOvh, SiPayoneer, SiPenny,
  SiPeugeot, SiPlaystation, SiQantas, SiQatarairways, SiRazer, SiRenault, SiRevolut, SiRewe, SiRossmann, SiRyanair, SiSeagate, SiSeat, SiSennheiser, SiShopee, SiSingaporeairlines, SiSkoda, SiSky, SiSony, SiSouthwestairlines, SiSparkasse,
  SiSpotify, SiStarbucks, SiStarlingbank, SiSteam, SiStrava, SiStripe, SiTarget, SiTesco, SiToyota, SiTripadvisor, SiTrivago, SiTurkishairlines, SiTwitch,
  SiUbereats, SiUnitedairlines, SiVenmo, SiVercel, SiVinted, SiVisa, SiVolvo,
  SiWise, SiXiaomi, SiYoutube,
  SiZabka, SiZalando, SiZara
} from 'react-icons/si'

import { AUSTRIAN_LOGOS } from './austrian-logos'
import {
  AceLogo,
  AdacEvLogo,
  AdacLogo,
  AutoClubEuropaLogo,
  AvdLogo,
} from './auto-club-logos'
import {
  ApoBankLogo,
  BunqLogo,
  C24Logo,
  ComdirectLogo,
  CommerzbankLogo,
  ConsorsbankLogo,
  DegiroLogo,
  DeutscheBankLogo,
  Direkt1822Logo,
  DkbLogo,
  EbaseLogo,
  ErsteBankLogo,
  FlatexLogo,
  FnzBankLogo,
  GlsBankLogo,
  HypoVereinsbankLogo,
  IngLogo,
  KlarnaLogo,
  N26Logo,
  NorisbankLogo,
  PostbankLogo,
  RevolutLogo,
  SantanderLogo,
  ScalableCapitalLogo,
  SpardaBankLogo,
  SparkasseLogo,
  TargobankLogo,
  TomorrowLogo,
  TradeRepublicLogo,
  VividMoneyLogo,
  VolksbankLogo,
  WiseLogo,
} from './bank-logos'
import {
  AudiLogo,
  BmwLogo,
  MercedesLogo,
  PorscheLogo,
  TeslaLogo,
  VolkswagenLogo,
} from './car-logos'
import {
  BadHomburgLogo,
  EdukativniCentarLogo,
  GermanyFlagLogo,
  HessenLogo,
  HochtaunuskreisLogo,
  KelkheimLogo,
  SchmittenLogo,
} from './civic-logos'
import { CIVIC_REGIONAL_LOGOS } from './civic-regional-logos'
import { CONSULAR_LOGOS } from './consular-logos'
import {
  LotharBraunLogo,
} from './craft-logos'
import {
  CoinbaseLogo,
  CRYPTO_LOGOS,
  GuardarianLogo,
  KrakenLogo,
} from './crypto-logos'
import { DINING_LOGOS, McdonaldsLogo } from './dining-logos'
import { DIY_LOGOS } from './diy-logos'
import { ENERGY_GRID_LOGOS } from './energy-grid-logos'
import { ENTERTAINMENT_LOGOS, NetflixLogo } from './entertainment-logos'
import { FASHION_LOGOS } from './fashion-logos'
import { FURNITURE_LOGOS, IkeaLogo } from './furniture-logos'
import {
  BadenWuerttembergFlagLogo,
  BayernFlagLogo,
  BerlinFlagLogo,
  BrandenburgFlagLogo,
  BremenFlagLogo,
  HamburgFlagLogo,
  HessenStateFlagLogo,
  MecklenburgVorpommernFlagLogo,
  NiedersachsenFlagLogo,
  NordrheinWestfalenFlagLogo,
  RheinlandPfalzFlagLogo,
  SaarlandFlagLogo,
  SachsenAnhaltFlagLogo,
  SachsenFlagLogo,
  SchleswigHolsteinFlagLogo,
  ThueringenFlagLogo,
} from './german-state-flags'
import { GROCERY_LOGOS } from './grocery-logos'
import {
  AokLogo,
  ApothekeLogo,
  BarmerLogo,
  DakLogo,
  DocMorrisLogo,
  MuenchenerVereinLogo,
  ShopApothekeLogo,
  TkLogo,
} from './health-logos'
import { HOSTEL_LOGOS } from './hostel-logos'
import { IDENTITY_LOGOS } from './identity-logos'
import { INSURANCE_LOGOS } from './insurance-logos'
import {
  FaerberHutzelLogo,
} from './legal-logos'
import { MOTORWAY_LOGOS } from './motorway-logos'
import { GooglePayLogo, PAYMENT_LOGOS, PaypalLogo, WesternUnionLogo } from './payment-logos'
import { PENSION_LOGOS } from './pension-logos'
import { PORTUGUESE_LOGOS } from './portuguese-logos'
import { PROPERTY_LOGOS } from './property-logos'
import {
  AmazonLogo,
  AppleLogo,
  BauhausLogo,
  CadoozLogo,
  CaLogo,
  CAndALogo,
  CHECK24Logo,
  Check24Logo,
  DellLogo,
  EbayLogo,
  EightAPLLogo,
  HornbachLogo,
  IntratecLogo,
  MediaMarktLogo,
  ObiLogo,
  PaybackLogo,
  PortraitnetLogo,
  SamsungLogo,
  ShopPortraitnetLogo,
  SnapOutdoorLogo,
  SumupLogo,
  TchiboLogo,
  WunschgutscheinLogo,
} from './retail-logos'
import { SPORTS_CLUB_LOGOS } from './sports-club-logos'
import {
  ElsterLogo,
  SmartsteuerLogo,
  TaxfixLogo,
  WisoSteuerLogo,
  WundertaxLogo,
} from './tax-logos'
import {
  CanonLogo,
  CloudflareLogo,
  CyberportLogo,
  HerokuLogo,
  HpLogo,
  LogitechLogo,
  MicrosoftLogo,
  PhilipsLogo,
} from './tech-logos'
import { O2Logo, TELECOM_LOGOS, VodafoneLogo } from './telecom-logos'
import { TOUR_OPERATOR_LOGOS } from './tour-operator-logos'
import {
  AralLogo,
  AsfinagLogo,
  AviaLogo,
  BpLogo,
  BvgLogo,
  DbLogo,
  EasyParkLogo,
  EnbwLogo,
  EniLogo,
  EssoLogo,
  FairParkenLogo,
  FastnedLogo,
  FlixLogo,
  HvvLogo,
  IonityLogo,
  JetLogo,
  OebbLogo,
  OmvLogo,
  RmvLogo,
  ShellLogo,
  SixtLogo,
  TotalEnergiesLogo,
  TurmoelLogo,
  UberLogo,
  VrrLogo,
} from './transit-logos'
import {
  AirportParkingGmbhLogo,
  AirportParkingLogo,
  AlltoursLogo,
  BookingLogo,
  CondorLogo,
  DertourLogo,
  EurowingsHolidaysLogo,
  EurowingsLogo,
  HolidaysLogo,
  SanderHotelLogo,
  SchauinslandLogo,
  TuiLogo,
  WizzAirLogo,
} from './travel-logos'
import type { IconComponent } from './types'
import {
  AldiTalkLogo,
  AllianzLogo,
  BeitragsserviceLogo,
  CongstarLogo,
  EinsUndEinsLogo,
  EonLogo,
  HukLogo,
  KlarmobilLogo,
  SuewagLogo,
  VattenfallLogo,
} from './utility-logos'
import { VARIETY_STORE_LOGOS } from './variety-store-logos'

export const MERCHANT_LOGOS: Record<string, IconComponent> = {
  SiNetflix: NetflixLogo,
  NetflixLogo,
  netflix: NetflixLogo,
  SiSpotify, SiStarbucks, SiSteam,
  SiUber: UberLogo,
  UberLogo,
  uber: UberLogo,
  SiMcdonalds: McdonaldsLogo,
  McdonaldsLogo,
  mcdonalds: McdonaldsLogo,
  "mcdonald's": McdonaldsLogo,
  IkeaLogo,
  SiIkea: IkeaLogo,
  'ikea': IkeaLogo,
  'IKEA': IkeaLogo,
  SiApple: AppleLogo,
  AppleLogo,
  apple: AppleLogo,
  PaypalLogo,
  PayPalLogo: PaypalLogo,
  SiPaypal: PaypalLogo,
  'paypal': PaypalLogo,
  'PayPal': PaypalLogo,
  SiAirbnb, SiNike, SiDm, SiRewe,
  SiKaufland,
  ShellLogo,
  SiShell: ShellLogo,
  shell: ShellLogo,
  Shell: ShellLogo,
  DbLogo,
  DeutscheBahnLogo: DbLogo,
  SiDeutschebahn: DbLogo,
  db: DbLogo,
  DB: DbLogo,
  SiDeutschetelekom,
  SiVodafone: VodafoneLogo,
  VodafoneLogo,
  vodafone: VodafoneLogo,
  SiO2: O2Logo,
  O2Logo,
  o2: O2Logo,
  AmazonLogo,
  FaAmazon: AmazonLogo,
  'amazon': AmazonLogo,
  'Amazon': AmazonLogo,
  SiAldisud,
  AralLogo,
  SiAral: AralLogo,
  aral: AralLogo,
  Aral: AralLogo,
  SiEdeka, SiLidl,
  SiZalando, SiTesco, SiShopee, SiOrange, SiGrab, SiGojek, SiDeliveroo,
  SiCarrefour, SiAllegro, SiJusteat,
  EbayLogo,
  SiEbay: EbayLogo,
  'ebay': EbayLogo,
  'eBay': EbayLogo,
  SiAuchan,
  BookingLogo,
  BookingDotComLogo: BookingLogo,
  SiBookingdotcom: BookingLogo,
  SiZabka, SiAsda, SiMorrisons, SiCoop, SiTarget, SiBurgerking, SiKfc,
  SiDoordash, SiUbereats, SiRevolut, SiWise,
  SiKlarna: KlarnaLogo,
  KlarnaLogo,
  KlarnaBankLogo: KlarnaLogo,
  klarna: KlarnaLogo,
  SiN26, SiMastercard,
  SiVisa, SiZara, SiLyft, SiYoutube, SiTwitch, SiPlaystation, SiSparkasse,
  SiWesternunion: WesternUnionLogo,
  WesternUnionLogo,
  westernunion: WesternUnionLogo,
  'western-union': WesternUnionLogo,
  'western union': WesternUnionLogo,
  SiMoneygram, SiApplepay, SiBankofamerica, SiBarclays, SiBinance,
  SiCashapp, SiChase,
  SiCoinbase: CoinbaseLogo,
  CoinbaseLogo,
  coinbase: CoinbaseLogo,
  SiCommerzbank: CommerzbankLogo,
  CommerzbankLogo,
  commerzbank: CommerzbankLogo,
  Commerzbank: CommerzbankLogo,
  SiDeutschebank: DeutscheBankLogo,
  DeutscheBankLogo,
  deutschebank: DeutscheBankLogo,
  'deutsche-bank': DeutscheBankLogo,
  'deutsche bank': DeutscheBankLogo,
  SiGlovo,
  GooglePayLogo,
  SiGooglepay: GooglePayLogo,
  GooglepayLogo: GooglePayLogo,
  GPayLogo: GooglePayLogo,
  'google-pay': GooglePayLogo,
  'google pay': GooglePayLogo,
  'gpay': GooglePayLogo,
  'GPay': GooglePayLogo,
  SiHsbc, SiMonzo, SiPayoneer, SiStripe, SiVenmo,
  SiRossmann,
  SiMediamarkt: MediaMarktLogo,
  MediaMarktLogo,
  MediamarktLogo: MediaMarktLogo,
  mediamarkt: MediaMarktLogo,
  'media-markt': MediaMarktLogo,
  SiVinted, SiAliexpress, SiEtsy, SiHellofresh,
  SiBunq, SiStarlingbank, SiEpicgames, SiDiscord, SiGithub, SiDuolingo, SiStrava,
  ComdirectLogo, DkbLogo, IngLogo, PostbankLogo, TradeRepublicLogo,
  ScalableCapitalLogo, VolksbankLogo, TargobankLogo, SpardaBankLogo, C24Logo, ConsorsbankLogo,
  TomorrowLogo, TomorrowBankLogo: TomorrowLogo,
  RmvLogo,
  rmv: RmvLogo,
  RMV: RmvLogo,
  HvvLogo, FlixLogo, OebbLogo, VrrLogo, BpLogo,
  TeslaLogo,
  SiTesla: TeslaLogo,
  tesla: TeslaLogo,
  Tesla: TeslaLogo,
  JetLogo, EssoLogo, AviaLogo, EniLogo, TurmoelLogo, AsfinagLogo, IonityLogo, EnbwLogo, FastnedLogo, SixtLogo,
  OmvLogo, omv: OmvLogo, OMV: OmvLogo,
  TotalEnergiesLogo, totalenergies: TotalEnergiesLogo, TotalEnergies: TotalEnergiesLogo,
  FairParkenLogo, EasyParkLogo,
  SiTui: TuiLogo,
  TuiLogo,
  tui: TuiLogo,
  TUI: TuiLogo,
  tuifly: TuiLogo,
  'tui-fly': TuiLogo,
  'tui-holidays': TuiLogo,
  'tui-reisen': TuiLogo,
  SiAirfrance, SiAmericanairlines, SiAircanada, SiBritishairways,
  BvgLogo,
  SiBvg: BvgLogo,
  bvg: BvgLogo,
  BVG: BvgLogo,
  SiDelta, SiEasyjet, SiEmirates,
  SiEtihadairways, SiExpedia, SiHilton, SiHotelsdotcom, SiKlm, SiLufthansa, SiMarriott, SiNetto,
  SiPenny, SiQantas, SiQatarairways, SiRyanair, SiSingaporeairlines, SiSouthwestairlines, SiTripadvisor,
  SiTrivago, SiTurkishairlines, SiUnitedairlines,
  SiWizzair: WizzAirLogo,
  WizzAirLogo,
  wizzair: WizzAirLogo,
  'wizz-air': WizzAirLogo,
  'wizz air': WizzAirLogo,
  DertourLogo,
  dertour: DertourLogo,
  DERTOUR: DertourLogo,
  AlltoursLogo,
  alltours: AlltoursLogo,
  Alltours: AlltoursLogo,
  SchauinslandLogo,
  schauinsland: SchauinslandLogo,
  Schauinsland: SchauinslandLogo,
  Check24Logo,
  CHECK24Logo,
  check24Logo: Check24Logo,
  'check24': Check24Logo,
  'CHECK24': Check24Logo,
  SumupLogo,
  SiDhl, SiDeutschepost, SiDazn, SiSky,
  BeitragsserviceLogo, TkLogo, AokLogo, EinsUndEinsLogo,
  SuewagLogo, EonLogo, VattenfallLogo,
  EurowingsLogo,
  EurowingsHolidaysLogo,
  HolidaysLogo,
  eurowings: EurowingsLogo,
  Eurowings: EurowingsLogo,
  holidays: EurowingsLogo,
  Holidays: EurowingsLogo,
  'holidays.ch': EurowingsLogo,
  'eurowings-holidays': EurowingsLogo,
  CondorLogo,
  condor: CondorLogo,
  Condor: CondorLogo,
  BarmerLogo, DakLogo, ShopApothekeLogo, DocMorrisLogo,
  ObiLogo, BauhausLogo, HornbachLogo, TchiboLogo, DellLogo,
  CaLogo,
  CAndALogo,
  'c-and-a': CaLogo,
  'C&A': CaLogo,
  'c&a': CaLogo,
  'ca': CaLogo,
  SiDell: DellLogo,
  SiHp,
  HpLogo,
  SiLenovo,
  SamsungLogo,
  samsung: SamsungLogo,
  SiSamsung: SamsungLogo,
  SiAsus,
  SiAcer,
  AcerLogo: SiAcer,
  SiMsi,
  MsiLogo: SiMsi,
  SiSony,
  SonyLogo: SiSony,
  SiLg,
  LgLogo: SiLg,
  MicrosoftLogo,
  FaMicrosoft,
  SiMicrosoft: MicrosoftLogo,
  LogitechLogo,
  CanonLogo,
  PhilipsLogo,
  SiNvidia,
  NvidiaLogo: SiNvidia,
  SiAmd,
  AmdLogo: SiAmd,
  SiIntel,
  IntelLogo: SiIntel,
  SiRazer,
  RazerLogo: SiRazer,
  SiXiaomi,
  XiaomiLogo: SiXiaomi,
  SiBose,
  BoseLogo: SiBose,
  SiCorsair,
  SiSennheiser,
  SiSeagate,
  SiEpson,
  SiHuawei,
  AllianzLogo, HukLogo,
  MercedesLogo,
  MercedesBenzLogo: MercedesLogo,
  mercedes: MercedesLogo,
  Mercedes: MercedesLogo,
  BmwLogo,
  bmw: BmwLogo,
  BMW: BmwLogo,
  AudiLogo,
  audi: AudiLogo,
  Audi: AudiLogo,
  VolkswagenLogo,
  VwLogo: VolkswagenLogo,
  volkswagen: VolkswagenLogo,
  VW: VolkswagenLogo,
  PorscheLogo,
  porsche: PorscheLogo,
  Porsche: PorscheLogo,
  SiToyota,
  SiFord,
  SiVolvo,
  SiRenault,
  SiSkoda,
  SiSeat,
  SiOpel,
  SiHyundai,
  SiHonda,
  SiKia,
  SiMazda,
  SiNissan,
  SiPeugeot,
  SiFiat,
  WundertaxLogo,
  wundertax: WundertaxLogo,
  TaxfixLogo,
  taxfix: TaxfixLogo,
  SmartsteuerLogo,
  smartsteuer: SmartsteuerLogo,
  ElsterLogo,
  elster: ElsterLogo,
  ELSTER: ElsterLogo,
  WisoSteuerLogo,
  'wiso-steuer': WisoSteuerLogo,
  'wiso': WisoSteuerLogo,
  GuardarianLogo,
  KrakenLogo,
  BadHomburgLogo,
  BadHomburgWappenLogo: BadHomburgLogo,
  StadtBadHomburgLogo: BadHomburgLogo,
  SchmittenLogo,
  SchmittenWappenLogo: SchmittenLogo,
  GemeindeSchmittenLogo: SchmittenLogo,
  KelkheimLogo,
  KelkheimWappenLogo: KelkheimLogo,
  StadtKelkheimLogo: KelkheimLogo,
  StadtkasseKelkheimLogo: KelkheimLogo,
  HochtaunuskreisLogo,
  KreisHochtaunusLogo: HochtaunuskreisLogo,
  LandkreisHochtaunusLogo: HochtaunuskreisLogo,
  EdukativniCentarLogo,
  edukativniCentarLogo: EdukativniCentarLogo,
  EdukativniCentarRaniRazvojLogo: EdukativniCentarLogo,
  RaniRazvojLogo: EdukativniCentarLogo,
  'edukativni-centar': EdukativniCentarLogo,
  'edukativni-centar-rani-razvoj': EdukativniCentarLogo,
  'rani-razvoj': EdukativniCentarLogo,
  HessenLogo,
  LandHessenLogo: HessenLogo,
  HessenFlagLogo: HessenLogo,
  HessenWappenLogo: HessenLogo,
  GerichtskasseHessenLogo: HessenLogo,
  GerichtskasseLogo: HessenLogo,
  gerichtskasse: HessenLogo,
  Gerichtskasse: HessenLogo,
  gerichtkasse: HessenLogo,
  Gerichtkasse: HessenLogo,
  justizkasse: HessenLogo,
  GermanyFlagLogo,
  FederalRepublicLogo: GermanyFlagLogo,
  BundesflaggeLogo: GermanyFlagLogo,
  FinanzamtLogo: GermanyFlagLogo,
  finanzamt: GermanyFlagLogo,
  Finanzamt: GermanyFlagLogo,
  BadenWuerttembergFlagLogo,
  BayernFlagLogo,
  BerlinFlagLogo,
  BrandenburgFlagLogo,
  BremenFlagLogo,
  HamburgFlagLogo,
  HessenStateFlagLogo,
  MecklenburgVorpommernFlagLogo,
  NiedersachsenFlagLogo,
  NordrheinWestfalenFlagLogo,
  RheinlandPfalzFlagLogo,
  SaarlandFlagLogo,
  SachsenFlagLogo,
  SachsenAnhaltFlagLogo,
  SchleswigHolsteinFlagLogo,
  ThueringenFlagLogo,
  FaerberHutzelLogo,
  FaerberUndHutzelLogo: FaerberHutzelLogo,
  FarberHutzelLogo: FaerberHutzelLogo,
  FarberUndHutzelLogo: FaerberHutzelLogo,
  IntratecLogo,
  IntraTecLogo: IntratecLogo,
  CadoozLogo,
  cadoozLogo: CadoozLogo,
  PaybackLogo,
  PaybackPayLogo: PaybackLogo,
  PaymorrowLogo: PaybackLogo,
  SiPayback: PaybackLogo,
  LotharBraunLogo,
  SchreinereiBraunLogo: LotharBraunLogo,
  SchreinereiLotharBraunLogo: LotharBraunLogo,
  'lothar-braun': LotharBraunLogo,
  'schreinerei-lothar-braun': LotharBraunLogo,
  RevolutLogo,
  RevoltLogo: RevolutLogo,
  RevolutBankLogo: RevolutLogo,
  SparkasseLogo,
  HaspaLogo: SparkasseLogo,
  Direkt1822Logo,
  Logo1822Direkt: Direkt1822Logo,
  '1822direktLogo': Direkt1822Logo,
  HypoVereinsbankLogo,
  HvbLogo: HypoVereinsbankLogo,
  UniCreditLogo: HypoVereinsbankLogo,
  SantanderLogo,
  SantanderDeutschlandLogo: SantanderLogo,
  NorisbankLogo,
  GlsBankLogo,
  FlatexLogo,
  DegiroLogo,
  VividMoneyLogo,
  VividLogo: VividMoneyLogo,
  ApoBankLogo,
  N26Logo,
  WiseLogo,
  BunqLogo,
  KlarmobilLogo,
  KlarmobilDeLogo: KlarmobilLogo,
  HerokuLogo,
  SiHeroku: HerokuLogo,
  heroku: HerokuLogo,
  CyberportLogo,
  cyberportLogo: CyberportLogo,
  'cyberport': CyberportLogo,
  FaAws,
  AwsLogo: FaAws,
  SiCloudflare: CloudflareLogo,
  CloudflareLogo,
  cloudflare: CloudflareLogo,
  SiDigitalocean,
  DigitalOceanLogo: SiDigitalocean,
  SiFreenet,
  FreenetLogo: SiFreenet,
  SiHetzner,
  HetznerLogo: SiHetzner,
  SiIonos,
  IonosLogo: SiIonos,
  SiNetcup,
  NetcupLogo: SiNetcup,
  SiOvh,
  OvhLogo: SiOvh,
  OVHcloudLogo: SiOvh,
  SiVercel,
  VercelLogo: SiVercel,
  CongstarLogo,
  congstarLogo: CongstarLogo,
  AldiTalkLogo,
  aldiTalkLogo: AldiTalkLogo,
  MuenchenerVereinLogo,
  muenchenerVereinLogo: MuenchenerVereinLogo,
  ApothekeLogo,
  apothekeLogo: ApothekeLogo,
  'apotheke': ApothekeLogo,
  'rats-apotheke': ApothekeLogo,
  'liebig-apotheke': ApothekeLogo,
  EbaseLogo,
  ebaseLogo: EbaseLogo,
  'ebase': EbaseLogo,
  FnzBankLogo,
  fnzBankLogo: FnzBankLogo,
  'fnz-bank': FnzBankLogo,
  'fnz': FnzBankLogo,
  SanderHotelLogo,
  sanderHotelLogo: SanderHotelLogo,
  'sander-hotel': SanderHotelLogo,
  ErsteBankLogo,
  ersteBankLogo: ErsteBankLogo,
  'erste-bank': ErsteBankLogo,
  WunschgutscheinLogo,
  wunschgutscheinLogo: WunschgutscheinLogo,
  'wunschgutschein': WunschgutscheinLogo,
  SnapOutdoorLogo,
  snapOutdoorLogo: SnapOutdoorLogo,
  'snap-outdoor': SnapOutdoorLogo,
  EightAPLLogo,
  '8a-pl': SnapOutdoorLogo,
  '8a': SnapOutdoorLogo,
  PortraitnetLogo,
  portraitnetLogo: PortraitnetLogo,
  'portraitnet': PortraitnetLogo,
  'shop-portraitnet': PortraitnetLogo,
  ShopPortraitnetLogo,
  AirportParkingLogo,
  airportParkingLogo: AirportParkingLogo,
  AirportParkingGmbhLogo,
  'airport-parking': AirportParkingLogo,
  ...AUSTRIAN_LOGOS,
  AdacLogo,
  AdacEvLogo,
  AceLogo,
  AutoClubEuropaLogo,
  AvdLogo,
  ...CIVIC_REGIONAL_LOGOS,
  ...CONSULAR_LOGOS,
  ...CRYPTO_LOGOS,
  ...DINING_LOGOS,
  ...DIY_LOGOS,
  ...ENERGY_GRID_LOGOS,
  ...ENTERTAINMENT_LOGOS,
  ...FASHION_LOGOS,
  ...FURNITURE_LOGOS,
  ...GROCERY_LOGOS,
  ...HOSTEL_LOGOS,
  ...IDENTITY_LOGOS,
  ...INSURANCE_LOGOS,
  ...MOTORWAY_LOGOS,
  ...PAYMENT_LOGOS,
  ...PENSION_LOGOS,
  ...PORTUGUESE_LOGOS,
  ...PROPERTY_LOGOS,
  ...SPORTS_CLUB_LOGOS,
  ...TELECOM_LOGOS,
  ...TOUR_OPERATOR_LOGOS,
  ...VARIETY_STORE_LOGOS,
}

export { DeutscheBankLogo, ErsteBankLogo, KlarnaBankLogo, KlarnaLogo } from './bank-logos'
export { CoinbaseLogo } from './crypto-logos'
export { BaeckereiMoosLogo, BrotchenmacherLogo, FeinkostStrahmannLogo, McdonaldsLogo, OkkaBakeryLogo, ThaiSnackLogo } from './dining-logos'
export { NetflixLogo } from './entertainment-logos'
export { AppleLogo, EightAPLLogo, MediaMarktLogo, MediamarktLogo, PortraitnetLogo, ShopPortraitnetLogo, SnapOutdoorLogo, WunschgutscheinLogo } from './retail-logos'
export { AirportParkingGmbhLogo, AirportParkingLogo, WizzAirLogo } from './travel-logos'
export { KinderplanetLogo } from './variety-store-logos'
export { AmazonLogo, CaLogo, CAndALogo, EbayLogo, GooglePayLogo, IkeaLogo, IntratecLogo, PaypalLogo }
export { LotharBraunLogo, SchreinereiBraunLogo, SchreinereiLotharBraunLogo } from './craft-logos'
export { WesternUnionLogo } from './payment-logos'
export { CloudflareLogo,HerokuLogo } from './tech-logos'
export { O2Logo, VodafoneLogo } from './telecom-logos'
export { UberLogo, UberRidesLogo } from './transit-logos'


