import { FaAmazon, FaAws, FaMicrosoft } from 'react-icons/fa'
import {
  SiAcer, SiAirbnb, SiAircanada, SiAirfrance, SiAldisud, SiAliexpress, SiAllegro, SiAmd, SiAmericanairlines, SiApple, SiApplepay, SiAral, SiAsda, SiAsus, SiAuchan,
  SiBankofamerica, SiBarclays, SiBinance, SiBose, SiBritishairways, SiBunq, SiBurgerking, SiBvg, SiCarrefour,
  SiCashapp, SiChase, SiCloudflare, SiCoinbase, SiCommerzbank, SiCoop, SiCorsair, SiDazn, SiDeliveroo,
  SiDelta, SiDeutschebahn, SiDeutschebank, SiDeutschepost, SiDeutschetelekom, SiDhl, SiDigitalocean, SiDiscord, SiDm, SiDoordash, SiDuolingo, SiEasyjet, SiEbay, SiEdeka,
  SiEmirates, SiEpicgames, SiEpson, SiEtihadairways, SiEtsy, SiExpedia, SiFiat, SiFord, SiFreenet, SiGithub, SiGlovo, SiGojek, SiGooglepay, SiGrab, SiHellofresh, SiHetzner, SiHilton, SiHonda, SiHotelsdotcom, SiHp, SiHsbc, SiHuawei, SiHyundai, SiIkea, SiIntel, SiIonos, SiJusteat, SiKaufland, SiKfc,
  SiKia, SiKlarna, SiKlm, SiLenovo, SiLg, SiLidl, SiLufthansa, SiLyft, SiMarriott, SiMastercard, SiMazda, SiMcdonalds, SiMediamarkt, SiMoneygram, SiMonzo,
  SiMorrisons, SiMsi, SiN26, SiNetcup, SiNetflix, SiNetto, SiNike, SiNissan, SiNvidia, SiO2, SiOpel, SiOrange, SiOvh, SiPayoneer, SiPaypal, SiPenny,
  SiPeugeot, SiPlaystation, SiQantas, SiQatarairways, SiRazer, SiRenault, SiRevolut, SiRewe, SiRossmann, SiRyanair, SiSamsung, SiSeagate, SiSeat, SiSennheiser, SiShell, SiShopee, SiSingaporeairlines, SiSkoda, SiSky, SiSony, SiSouthwestairlines, SiSparkasse,
  SiSpotify, SiStarbucks, SiStarlingbank, SiSteam, SiStrava, SiStripe, SiTarget, SiTesco, SiTesla, SiToyota, SiTripadvisor, SiTrivago, SiTui, SiTurkishairlines, SiTwitch, SiUber,
  SiUbereats, SiUnitedairlines, SiVenmo, SiVercel, SiVinted, SiVisa, SiVodafone, SiVolvo,
  SiWesternunion, SiWise, SiWizzair, SiXiaomi, SiYoutube,
  SiZabka, SiZalando, SiZara
} from 'react-icons/si'

import { AUSTRIAN_LOGOS } from './austrian-logos'
import { AUTO_CLUB_LOGOS } from './auto-club-logos'
import {
  ApoBankLogo,
  BunqLogo,
  C24Logo,
  ComdirectLogo,
  ConsorsbankLogo,
  DegiroLogo,
  Direkt1822Logo,
  DkbLogo,
  FlatexLogo,
  GlsBankLogo,
  HypoVereinsbankLogo,
  IngLogo,
  N26Logo,
  NorisbankLogo,
  PostbankLogo,
  RevolutLogo,
  SantanderLogo,
  ScalableCapitalLogo,
  SpardaBankLogo,
  SparkasseLogo,
  TargobankLogo,
  TomorrowLogo,
  TradeRepublicLogo,
  VividMoneyLogo,
  VolksbankLogo,
  WiseLogo,
} from './bank-logos'
import {
  AudiLogo,
  BmwLogo,
  MercedesLogo,
  PorscheLogo,
  VolkswagenLogo,
} from './car-logos'
import {
  BadHomburgLogo,
  GermanyFlagLogo,
  HessenLogo,
  HochtaunuskreisLogo,
  KelkheimLogo,
  SchmittenLogo,
} from './civic-logos'
import { CONSULAR_LOGOS } from './consular-logos'
import {
  LotharBraunLogo,
} from './craft-logos'
import {
  CRYPTO_LOGOS,
  GuardarianLogo,
  KrakenLogo,
} from './crypto-logos'
import { ENERGY_GRID_LOGOS } from './energy-grid-logos'
import { ENTERTAINMENT_LOGOS } from './entertainment-logos'
import { FASHION_LOGOS } from './fashion-logos'
import { FURNITURE_LOGOS } from './furniture-logos'
import {
  BadenWuerttembergFlagLogo,
  BayernFlagLogo,
  BerlinFlagLogo,
  BrandenburgFlagLogo,
  BremenFlagLogo,
  HamburgFlagLogo,
  HessenStateFlagLogo,
  MecklenburgVorpommernFlagLogo,
  NiedersachsenFlagLogo,
  NordrheinWestfalenFlagLogo,
  RheinlandPfalzFlagLogo,
  SaarlandFlagLogo,
  SachsenAnhaltFlagLogo,
  SachsenFlagLogo,
  SchleswigHolsteinFlagLogo,
  ThueringenFlagLogo,
} from './german-state-flags'
import {
  AokLogo,
  BarmerLogo,
  DakLogo,
  DocMorrisLogo,
  MuenchenerVereinLogo,
  ShopApothekeLogo,
  TkLogo,
} from './health-logos'
import { HOSTEL_LOGOS } from './hostel-logos'
import { IDENTITY_LOGOS } from './identity-logos'
import { INSURANCE_LOGOS } from './insurance-logos'
import {
  FaerberHutzelLogo,
} from './legal-logos'
import { PAYMENT_LOGOS } from './payment-logos'
import { PENSION_LOGOS } from './pension-logos'
import {
  BauhausLogo,
  CadoozLogo,
  Check24Logo,
  DellLogo,
  HornbachLogo,
  IntratecLogo,
  ObiLogo,
  PaybackLogo,
  SumupLogo,
  TchiboLogo,
} from './retail-logos'
import { SPORTS_CLUB_LOGOS } from './sports-club-logos'
import {
  ElsterLogo,
  SmartsteuerLogo,
  TaxfixLogo,
  WisoSteuerLogo,
  WundertaxLogo,
} from './tax-logos'
import {
  CanonLogo,
  HerokuLogo,
  HpLogo,
  LogitechLogo,
  MicrosoftLogo,
  PhilipsLogo,
} from './tech-logos'
import { TELECOM_LOGOS } from './telecom-logos'
import { TOUR_OPERATOR_LOGOS } from './tour-operator-logos'
import {
  AsfinagLogo,
  AviaLogo,
  BpLogo,
  EasyParkLogo,
  EnbwLogo,
  EniLogo,
  EssoLogo,
  FairParkenLogo,
  FastnedLogo,
  FlixLogo,
  HvvLogo,
  IonityLogo,
  JetLogo,
  OebbLogo,
  RmvLogo,
  SixtLogo,
  TurmoelLogo,
  VrrLogo,
} from './transit-logos'
import {
  AlltoursLogo,
  BookingLogo,
  CondorLogo,
  DertourLogo,
  EurowingsLogo,
  SchauinslandLogo,
  TuiLogo,
} from './travel-logos'
import type { IconComponent } from './types'
import {
  AldiTalkLogo,
  AllianzLogo,
  BeitragsserviceLogo,
  CongstarLogo,
  EinsUndEinsLogo,
  EonLogo,
  HukLogo,
  KlarmobilLogo,
  SuewagLogo,
  VattenfallLogo,
} from './utility-logos'

export const MERCHANT_LOGOS: Record<string, IconComponent> = {
  SiNetflix, SiSpotify, SiUber, SiStarbucks, SiSteam, SiMcdonalds,
  SiIkea, SiApple, SiPaypal, SiAirbnb, SiNike, SiDm, SiRewe,
  SiKaufland, SiShell, SiDeutschebahn, SiDeutschetelekom, SiVodafone, SiO2,
  FaAmazon, SiAldisud, SiAral, SiEdeka, SiLidl,
  SiZalando, SiTesco, SiShopee, SiOrange, SiGrab, SiGojek, SiDeliveroo,
  SiCarrefour, SiAllegro, SiJusteat, SiEbay, SiAuchan,
  BookingLogo,
  BookingDotComLogo: BookingLogo,
  SiBookingdotcom: BookingLogo,
  SiZabka, SiAsda, SiMorrisons, SiCoop, SiTarget, SiBurgerking, SiKfc,
  SiDoordash, SiUbereats, SiRevolut, SiWise, SiKlarna, SiN26, SiMastercard,
  SiVisa, SiZara, SiLyft, SiYoutube, SiTwitch, SiPlaystation, SiSparkasse,
  SiWesternunion, SiMoneygram, SiApplepay, SiBankofamerica, SiBarclays, SiBinance,
  SiCashapp, SiChase, SiCoinbase, SiCommerzbank, SiDeutschebank, SiGlovo,
  SiGooglepay, SiHsbc, SiMonzo, SiPayoneer, SiStripe, SiVenmo,
  SiRossmann, SiMediamarkt, SiVinted, SiAliexpress, SiEtsy, SiHellofresh,
  SiBunq, SiStarlingbank, SiEpicgames, SiDiscord, SiGithub, SiDuolingo, SiStrava,
  ComdirectLogo, DkbLogo, IngLogo, PostbankLogo, TradeRepublicLogo,
  ScalableCapitalLogo, VolksbankLogo, TargobankLogo, SpardaBankLogo, C24Logo, ConsorsbankLogo,
  TomorrowLogo, TomorrowBankLogo: TomorrowLogo,
  RmvLogo, HvvLogo, FlixLogo, OebbLogo, VrrLogo, BpLogo,
  SiTesla, JetLogo, EssoLogo, AviaLogo, EniLogo, TurmoelLogo, AsfinagLogo, IonityLogo, EnbwLogo, FastnedLogo, SixtLogo,
  FairParkenLogo, EasyParkLogo,
  SiTui, TuiLogo,
  SiAirfrance, SiAmericanairlines, SiAircanada, SiBritishairways, SiBvg, SiDelta, SiEasyjet, SiEmirates,
  SiEtihadairways, SiExpedia, SiHilton, SiHotelsdotcom, SiKlm, SiLufthansa, SiMarriott, SiNetto,
  SiPenny, SiQantas, SiQatarairways, SiRyanair, SiSingaporeairlines, SiSouthwestairlines, SiTripadvisor,
  SiTrivago, SiTurkishairlines, SiUnitedairlines, SiWizzair,
  DertourLogo, AlltoursLogo, SchauinslandLogo, Check24Logo, SumupLogo,
  SiDhl, SiDeutschepost, SiDazn, SiSky,
  BeitragsserviceLogo, TkLogo, AokLogo, EinsUndEinsLogo,
  SuewagLogo, EonLogo, VattenfallLogo, EurowingsLogo, CondorLogo,
  BarmerLogo, DakLogo, ShopApothekeLogo, DocMorrisLogo,
  ObiLogo, BauhausLogo, HornbachLogo, TchiboLogo, DellLogo,
  SiDell: DellLogo,
  SiHp,
  HpLogo,
  SiLenovo,
  SiSamsung,
  SiAsus,
  SiAcer,
  AcerLogo: SiAcer,
  SiMsi,
  MsiLogo: SiMsi,
  SiSony,
  SonyLogo: SiSony,
  SiLg,
  LgLogo: SiLg,
  MicrosoftLogo,
  FaMicrosoft,
  SiMicrosoft: MicrosoftLogo,
  LogitechLogo,
  CanonLogo,
  PhilipsLogo,
  SiNvidia,
  NvidiaLogo: SiNvidia,
  SiAmd,
  AmdLogo: SiAmd,
  SiIntel,
  IntelLogo: SiIntel,
  SiRazer,
  RazerLogo: SiRazer,
  SiXiaomi,
  XiaomiLogo: SiXiaomi,
  SiBose,
  BoseLogo: SiBose,
  SiCorsair,
  SiSennheiser,
  SiSeagate,
  SiEpson,
  SiHuawei,
  AllianzLogo, HukLogo,
  MercedesLogo,
  MercedesBenzLogo: MercedesLogo,
  BmwLogo,
  AudiLogo,
  VolkswagenLogo,
  VwLogo: VolkswagenLogo,
  PorscheLogo,
  SiToyota,
  SiFord,
  SiVolvo,
  SiRenault,
  SiSkoda,
  SiSeat,
  SiOpel,
  SiHyundai,
  SiHonda,
  SiKia,
  SiMazda,
  SiNissan,
  SiPeugeot,
  SiFiat,
  WundertaxLogo,
  TaxfixLogo,
  SmartsteuerLogo,
  ElsterLogo,
  WisoSteuerLogo,
  GuardarianLogo,
  KrakenLogo,
  BadHomburgLogo,
  BadHomburgWappenLogo: BadHomburgLogo,
  StadtBadHomburgLogo: BadHomburgLogo,
  SchmittenLogo,
  SchmittenWappenLogo: SchmittenLogo,
  GemeindeSchmittenLogo: SchmittenLogo,
  KelkheimLogo,
  KelkheimWappenLogo: KelkheimLogo,
  StadtKelkheimLogo: KelkheimLogo,
  StadtkasseKelkheimLogo: KelkheimLogo,
  HochtaunuskreisLogo,
  KreisHochtaunusLogo: HochtaunuskreisLogo,
  LandkreisHochtaunusLogo: HochtaunuskreisLogo,
  HessenLogo,
  LandHessenLogo: HessenLogo,
  HessenFlagLogo: HessenLogo,
  HessenWappenLogo: HessenLogo,
  GerichtskasseHessenLogo: HessenLogo,
  GermanyFlagLogo,
  FederalRepublicLogo: GermanyFlagLogo,
  BundesflaggeLogo: GermanyFlagLogo,
  FinanzamtLogo: GermanyFlagLogo,
  BadenWuerttembergFlagLogo,
  BayernFlagLogo,
  BerlinFlagLogo,
  BrandenburgFlagLogo,
  BremenFlagLogo,
  HamburgFlagLogo,
  HessenStateFlagLogo,
  MecklenburgVorpommernFlagLogo,
  NiedersachsenFlagLogo,
  NordrheinWestfalenFlagLogo,
  RheinlandPfalzFlagLogo,
  SaarlandFlagLogo,
  SachsenFlagLogo,
  SachsenAnhaltFlagLogo,
  SchleswigHolsteinFlagLogo,
  ThueringenFlagLogo,
  FaerberHutzelLogo,
  FaerberUndHutzelLogo: FaerberHutzelLogo,
  FarberHutzelLogo: FaerberHutzelLogo,
  FarberUndHutzelLogo: FaerberHutzelLogo,
  IntratecLogo,
  IntraTecLogo: IntratecLogo,
  CadoozLogo,
  cadoozLogo: CadoozLogo,
  PaybackLogo,
  PaybackPayLogo: PaybackLogo,
  PaymorrowLogo: PaybackLogo,
  SiPayback: PaybackLogo,
  LotharBraunLogo,
  SchreinereiBraunLogo: LotharBraunLogo,
  SchreinereiLotharBraunLogo: LotharBraunLogo,
  RevolutLogo,
  RevoltLogo: RevolutLogo,
  RevolutBankLogo: RevolutLogo,
  SparkasseLogo,
  HaspaLogo: SparkasseLogo,
  Direkt1822Logo,
  Logo1822Direkt: Direkt1822Logo,
  '1822direktLogo': Direkt1822Logo,
  HypoVereinsbankLogo,
  HvbLogo: HypoVereinsbankLogo,
  UniCreditLogo: HypoVereinsbankLogo,
  SantanderLogo,
  SantanderDeutschlandLogo: SantanderLogo,
  NorisbankLogo,
  GlsBankLogo,
  FlatexLogo,
  DegiroLogo,
  VividMoneyLogo,
  VividLogo: VividMoneyLogo,
  ApoBankLogo,
  N26Logo,
  WiseLogo,
  BunqLogo,
  KlarmobilLogo,
  KlarmobilDeLogo: KlarmobilLogo,
  HerokuLogo,
  SiHeroku: HerokuLogo,
  FaAws,
  AwsLogo: FaAws,
  SiCloudflare,
  CloudflareLogo: SiCloudflare,
  SiDigitalocean,
  DigitalOceanLogo: SiDigitalocean,
  SiFreenet,
  FreenetLogo: SiFreenet,
  SiHetzner,
  HetznerLogo: SiHetzner,
  SiIonos,
  IonosLogo: SiIonos,
  SiNetcup,
  NetcupLogo: SiNetcup,
  SiOvh,
  OvhLogo: SiOvh,
  OVHcloudLogo: SiOvh,
  SiVercel,
  VercelLogo: SiVercel,
  CongstarLogo,
  congstarLogo: CongstarLogo,
  AldiTalkLogo,
  aldiTalkLogo: AldiTalkLogo,
  MuenchenerVereinLogo,
  muenchenerVereinLogo: MuenchenerVereinLogo,
  ...AUSTRIAN_LOGOS,
  ...AUTO_CLUB_LOGOS,
  ...CONSULAR_LOGOS,
  ...CRYPTO_LOGOS,
  ...ENERGY_GRID_LOGOS,
  ...ENTERTAINMENT_LOGOS,
  ...FASHION_LOGOS,
  ...FURNITURE_LOGOS,
  ...HOSTEL_LOGOS,
  ...IDENTITY_LOGOS,
  ...INSURANCE_LOGOS,
  ...PAYMENT_LOGOS,
  ...PENSION_LOGOS,
  ...SPORTS_CLUB_LOGOS,
  ...TELECOM_LOGOS,
  ...TOUR_OPERATOR_LOGOS,
}
